doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
        schema_filter: '~^(?!messenger_messages|user_followers)~'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/App/Entity'
                prefix: 'App\Entity'
                alias: App
            CheeperDomainModel:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Cheeper/Infrastructure/Persistence/DoctrineMappings'
                prefix: 'Cheeper\DomainModel'
                alias: CheeperDomainModel
