nelmio_api_doc:
    documentation:
        info:
            title: Cheeper API
            description: Cheeper is a twitter clone!
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
