nelmio_api_doc:
    documentation:
        info:
            title: Cheeper API
            description: Cheeper is a twitter clone!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/docs)
