services:
  mysql:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db
  app:
    image: ghcr.io/dddshelf/cheeper-ddd-cqrs-example/app:${DOCKER_IMAGE_TAG:-latest}
    build:
      dockerfile: Dockerfile
      context: .
      target: local
    init: true
    env_file: .env.docker.dist
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html