name: CI
on:
  pull_request:
  push:

env:
  DOCKER_IMAGE_TAG: ${{ github.sha }}

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: "Install BuildX"
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: DOCKER IMAGES
        uses: docker/build-push-action@v3
        with:
          load: true
          file: Dockerfile
          context: .
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/dddshelf/cheeper-ddd-cqrs-example/app:latest
            ghcr.io/dddshelf/cheeper-ddd-cqrs-example/app:${{ github.sha }}

      - name: STATIC ANALISYS
        run: make psalm-github

      - name: UNIT TESTS
        run: make unit-tests

      - name: FUNCTIONAL TESTS
        run: make functional-tests

      - name: CODE STYLE
        run: make check-cs

      - name: DEPTRACK
        run: make deptrack

      - name: INFECTION
        run: make mutation-tests